### ISSUE TITLE
criar página de cadastro de Consulta

### ISSUE THREAD

**Issue by luturol** [tudoNoob/poseidon#17]

**Comment by luturol** [comment]
Criar uma página com drop box de data e hora vagos e com pesquisa direta de paciente

**Comment by luturol** [comment]
tem que retornar um JSON do server,  se liga tal ez de para usar um outro tipo de controller chamado RestController. isso só se aplica se tu for criar um novo controller para executar esta ação

**Comment by willmenn** [comment]
Deverá ser criada uma nov issue para consulta, já que mudamos como iremos fazer.
