### ISSUE TITLE
Resolver o problema no cadastro da Consulta

### ISSUE THREAD

**Issue by matuella** [tudoNoob/poseidon#50]
O erro está possivelmente no parse do campo horario_consulta no cadastrarConsulta.html, de ("HH:mm:ss") para java.util.Date.

**Comment by willmenn** [comment]
Irei fazer, estou meio ocupado esta semana, mas no findi estará feito.

2016-01-21 21:42 GMT-02:00 Guilherme Carlos Matuella <
notifications@github.com>:

**Comment by willmenn** [comment]
Vou fechar já que estamos com problemas na consulta, e tem outra issue para resolver.
