### ISSUE TITLE
Add mascara para SP

### ISSUE THREAD

**Issue by willmenn** [tudoNoob/poseidon#78]

**Comment by matuella** [comment]
O que seria SP?

**Comment by willmenn** [comment]
Sao paulo.

**Comment by matuella** [comment]
o que tu acha de aumentar o tamanho do input? 
Ex.: Ele aceitaria: "(000) 0000-0000" ou "(000) 00000-0000".
Ou seja, na máscara : **minlength** == 15, **maxlength** == 16.

**Comment by willmenn** [comment]
Concordo.
