### ISSUE TITLE
Mudar nome de Mécido para Quiropraxia

### ISSUE THREAD

**Issue by willmenn** [tudoNoob/poseidon#81]

**Comment by matuella** [comment]
Tu diz refatorar tudo que está escrito Médico pra Quiropraxista?

**Comment by willmenn** [comment]
Isso mesmo, pois a gnete nao está fazendo um software de clinica para médicos e sim para quiropraxistas  né, hehehe

**Comment by matuella** [comment]
@willmenn faz sentido hahaha

**Comment by willmenn** [comment]
@matuella  abre um branch para fazer isto. E depois submete em um pull request.

**Comment by luturol** [comment]
O software pode ser usado tanto pra clínica de quiropraxia quanto pra clínica de médico. Não foi feito algo específico de quiropraxia, não é?

**Comment by willmenn** [comment]
Não te entendi, tipo esse software é específico, ele seria só apra clinicas de quiropraxia, assim diminuindo o nicho e não deixando o software tao genérico que é nisso que esses sfotwares pecam, pois eles querem abranger o nicho de consumidores, porém deixam tudo genérico, o intuíito é diminuir o produto, deixar ele enxuto, perfeito e preciso no que precisa um software de clinicas de quiropraxia. :+1:

**Comment by matuella** [comment]
Concordo com o @willmenn , e em partes concordo contigo @luturol .
No quesito de "clínicas de quiropraxia": quanto mais específico tu for, mais tu vai chamar atenção em um nicho específico - como o will falou -  e tu vai acertar em cheio (é a ideia) nas necessidades daquele nicho.
No quesito de "clínicas no geral": acho que posteriormente podemos até fazer algo mais abstrato a partir desse, podendo adaptar qual for a tua especialização médica (ou uma clínica)... mas isso é papo pra outro projeto!

**Comment by willmenn** [comment]
@matuella  e  @luturol , o por que da gente não fazer um software abrangete?
-  A gente não conseguiria vencer em número de funcionalidades para compertir com um outro fornecedor que paga os programadores, e não são de fim de semana. Por isto quanto mais a gente diminuir o leque de pessoas que possam usar o nosso software a gente vai conseguir fazer um software **específico**, porém **bom**, pois ele fará exatamente o que este nicho **precisa** e **quer**.
